# Generated by Django 5.2.1 on 2025-06-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_newrecipe_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='createuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
